services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: yi_node
    container_name: yi_node
    ports:
      - 29992:29992
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./node:/usr/src/app
  postgres:
    image: postgres
    container_name: yi_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432  
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

